# Generated by Django 5.2.4 on 2025-07-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_first_name_customuser_contact_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pass_field',
        ),
    ]
